package privilege

import (
	"errors"
	"fmt"
	"path"
	"regexp"
	"strings"
)

var serviceUserRE = regexp.MustCompile("^[a-z_][a-z0-9_-]{0,31}$")

func SudoersRule(serviceUser, helperPath string) (string, error) {
	serviceUser = strings.TrimSpace(serviceUser)
	helperPath = strings.TrimSpace(helperPath)

	if !serviceUserRE.MatchString(serviceUser) {
		return "", errors.New("service user must match [a-z_][a-z0-9_-]{0,31}")
	}
	if helperPath == "" || !path.IsAbs(helperPath) {
		return "", errors.New("helper path must be absolute")
	}
	if strings.ContainsAny(helperPath, " \t\r\n,:\\") {
		return "", errors.New("helper path contains unsupported sudoers characters")
	}

	return fmt.Sprintf(
		"# Generated by nginx-manager. Install as /etc/sudoers.d/nginx-manager with mode 0440.\n%s ALL=(root) NOPASSWD: %s privileged apply\n",
		serviceUser,
		helperPath,
	), nil
}
